### PR TITLE
add service tags as separate metrics

### PR DESCRIPTION
**Pull request by jeinwag**
Add metrics containing the tags for each service as proposed in #45.

### CODE REVIEW

**Comment by grobie** [comment]
Thanks, on my review queue. I guess we should rename the flag and maybe even change this healthy metric. I'll think about it.

**Comment by brian-brazil** [comment]
This should probably be a time series per tag.

**Comment by iksaif** [comment]
Wouldn't having a time series per tag be huge ? That would work with a very small consul setup, but when you have one consul instance per datacenter you have ~ 10k nodes, 1k services and probably ~5k tags (minimum).

**Comment by grobie** [comment]
A time series with a constant value of 1 can be stored very efficiently, it's not something you need to worry about usually. Prometheus can store constant time series in the order of 100k samples per kilobyte.

**Comment by iksaif** [comment]
Yep, but generating and parsing /metrics is significantly slower when you have a lot of metrics. Especially if the client doesn't allow prometheus to pre-filter the metrics it's going to ask (/metrics?match[]=foo&match[]=bar.* for example, I don't know if the golang lib allows that)

**Comment by jeinwag** [comment]
Any chance on moving this forward?

**Comment by grobie** [comment]
Merged 1e37ab79d023c21fc6984b0f76270b4bd62a760b in master.

**Pull request closed without merging**
