### PR TITLE
Add label with consul service name to health summary.

### PR DESCRIPTION
**Pull request by jeinwag**
@grobie Fix for #15

### CODE REVIEW

**Comment by bsphere** [comment]
when is this going to be merged

**Comment by grobie** [comment]
I'll have a look at it today finally.

**Comment by epa095** [comment]
Status?

**Comment by mad01** [comment]
any reason why this is not merged ?

**Comment by grobie** [comment]
@jeinwag Finally getting to consul_exporter, sorry for the delay. I think we should be explicit and use `service_id` and `service_name` as labels to avoid any confusion. What do you think? Do you have time to send an update?

**Comment by jeinwag** [comment]
@grobie sure, I just  renamed the existing service label to service_id.

**Comment by NoumanSaleem** [comment]
thanks @jeinwag and @grobie !

**Pull request merged**
