### PR TITLE
health status and service tags as labels

### PR DESCRIPTION
**Pull request by avthart**
@grobie 

We would like to have the consul health status as a label so that we see if a node, service or check is "passing", "critical" or "warning". Besides that it's also useful to have the consul service tags as label.

This pull request resolves the following issues:
- #45
- #46

### CODE REVIEW

**Comment by nickvth** [comment]
@grobie can you please review and merge this pull request?

**Comment by wombledmaize** [comment]
I see the benefits of this feature, @grobie could you please review and merge this pull request?

**Comment by grobie** [comment]
I will once I have access to a computer again. The current ways of setting
both status and tags labels will cause problems though, so I'm not sure
this can be merged in this state. I'll explain once I ran some tests.

Opening separate PRs for these two independent changes would make reviews
easier.

**Comment by avthart** [comment]
@grobie 

We have tested this change on our prometheus test environment and it works as expected.

**Comment by grobie** [comment]
Thanks a lot for your contribution and I'm sorry for the late response. I have been traveling for the last 6 months.

I'm not sure how you're not running into staleness issues with your current approach. I'd expect to experience a delay of 5 minutes (default staleness delta) until alerts successfully update after all possible state changes.

I have a couple of change requests and issues with the current proposal. As two unrelated changes were mixed together, I commented on each individual issue (#45 and #46) to make it easier to follow the conversation. Please check my comments on these issues and follow up there or with separate pull requests for each one. I'm more than happy to merge solutions to the requests.

**Pull request closed without merging**
